import Head from 'next/head' 
import { Inter } from 'next/font/google' 
import Hero from '@/components/flowFusion/Hero'
import Navbars from '@/components/flowFusion/Navbars'
import Features from '@/components/flowFusion/Features'
import Cases from '@/components/flowFusion/Cases'
import Community from '@/components/flowFusion/Community'
import Footer from '@/components/flowFusion/Footer'
import CallAction from '@/components/flowFusion/CallAction'


const aiBot = () => {
    return (

      
        <>
        <Head>
        <title>flowfusion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-wrapper"> 
        <Navbars/>
        <Hero/>
        <Features/>
        <Cases/>
        <Community/>
        <CallAction/>
        <Footer/>
      </main>
    </>
    )
}

export default aiBot