 
import Head from 'next/head' 
import { Inter } from 'next/font/google'   
import Navbars from '@/components/founder/Navbars'
import Footer from '@/components/founder/Footer'
import Hero from '@/components/founder/Hero' 
import Investments from '@/components/founder/Investments'


const inter = Inter({ subsets: ['latin'] })

const founders = () => {
    return ( 
        <>
        <Head>
            <title>Founders Pass</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="main-wrapper founders-wrapper"> 
            <Navbars/>
            <Hero/>
  
            {/* <Investments/> */}

            <Footer/>
        </main>
        </>
    )
}

export default founders 