'use client';
import Promo from '@/components/Home/Promo';
import Hero from '@/components/Home/Hero'; 
import Head from 'next/head';  
import Blockchain from '@/components/Home/Blockchain';
import Products from '@/components/Home/Products';
import Faq from '@/components/Home/Faq';
import CallToAction from '@/components/Home/CallToAction';
import HomeNav from '@/components/Home/Navbars';
import About from '@/components/Home/About';
import HomeFooter from '@/components/Home/Footer';

export default function Home() { 
  return (
    <>
     <Head>
        <title>Myntist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home-wrapper">
        <HomeNav/>
        <Hero/>
        <Promo/>
        <About/>
        <Blockchain/>
        <Products/>
        <Faq/>
        <CallToAction/>
        <HomeFooter/>
      </main>
    </>
  )
}
