import Head from 'next/head' 
import { Inter } from 'next/font/google'  
import Navbars from '@/components/flowFusion/Navbars' 
import Footer from '@/components/flowFusion/Footer' 
import Pricing from '@/components/Pricing/Pricing'


const inter = Inter({ subsets: ['latin'] })

const pricing = () => {
    return (
        <>
        <Head>
        <title>Myntist Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-wrapper"> 
        <Navbars/>
        <Pricing/>
        <Footer/>
      </main>
    </>
    )
}

export default pricing 