import Head from 'next/head' 
import { Inter } from 'next/font/google'   
import TrandingPosts from '@/components/Treasurebox/TrandingPosts'
import Footer from '@/components/Treasurebox/Footer' 
import Hero from '@/components/Treasurebox/Hero'
import Treasurebox from '@/components/Treasurebox/Treasurebox'
import Testimonial from '@/components/Treasurebox/Testimonial'
import TreasureboxNav from '@/components/Treasurebox/Navbars'
import CallAction from '@/components/Treasurebox/CallAction'

const inter = Inter({ subsets: ['latin'] })

const treasurebox = () => {
    return (
        <>
        <Head>
        <title>Myntist Treasurebox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="treasurebox-wrapper"> 
        <TreasureboxNav/>
        <Hero/>
        <Treasurebox/>  
        <TrandingPosts/>
        <Testimonial/>
        <CallAction/>
        <Footer/>
      </main>
    </>
    )
}

export default treasurebox